name: Release
on: [workflow_dispatch]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v2.1.4

    - uses: actions/checkout@v2

    - name: git/unshallow
      run: git fetch --prune --unshallow

    - name: semantic-release
      run: npx -p @semantic-release/changelog -p semantic-release -p @semantic-release/git semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
