name: Release
on: [workflow_dispatch]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: git/unshallow
      run: git fetch --prune --unshallow

    - uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
